### ISSUE TITLE
TOA5 to CSV

### ISSUE THREAD

**Issue by mebloch** [xenobardok/ULM-Carbon-data-query-system#1]
[16_Jan_14 to 5_Feb_14.txt](https://github.com/SunilJamkatel/ULM-Carbon-data-query-system/files/2891110/16_Jan_14.to.5_Feb_14.txt)

Sunil,
The 2013-2014 data is in card converted TOA5 format. Therefore, it is not showing up when I try to card convert again. Can you determine a way to convert the TOA5 format to CSV so we can upload it to the query. Thanks!

**Comment by xenobardok** [comment]
Hey Melissa,

Sorry for the late reply. Every file has to be a valid .csv file without headings and has to be exactly 113 columns for the app to work. If you have a non-converted file for this date range, please use the procedures that I mentioned on the paper to convert it into csv. That is the only format the app would take right now. If this is the only file you have, we might have to tweak this file to convert it into csv. I might be able to come to the lab some day to show you how it can be done.
